Cirici\ApiBundle\Entity\AccessToken:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Cirici\ApiBundle\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: Cirici\ApiBundle\Model\UserInterface

    lifecycleCallbacks: {  }
