Cirici\ApiBundle\Entity\AuthCode:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Cirici\ApiBundle\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: Cirici\ApiBundle\Entity\User

    lifecycleCallbacks: {  }
