Cirici\ApiBundle\Entity\User:
    type: entity
    table: api_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    lifecycleCallbacks: {  }
